name: autoinvoice
run-name: Build and run AutoInvoice

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 1 * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven
      - name: Build
        run: mvn -B package
      - name: Rename
        run: mv target/autoinvoice-*.jar autoinvoice.jar
      - name: run
        run: java -jar autoinvoice.jar
        env:
          autoinvoice.user-id: ${{ secrets.USER_ID }}
          autoinvoice.user-email: ${{ secrets.USER_EMAIL }}
          autoinvoice.target-email: ${{ secrets.TARGET_EMAIL }}
          autoinvoice.credentials-b64: ${{ secrets.GOOGLE_CREDENTIALS }}
          autoinvoice.chat-webhook: ${{ secrets.CHAT_WEBHOOK }}
          fakturownia.base-domain: ${{ secrets.FAKTUROWNIA_BASE_URL }}
          fakturownia.token: ${{ secrets.FAKTUROWNIA_TOKEN }}
